[package]
name = "geocoding"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
colored = "3.0.0"
comfy-table = { version = "7.1.4", features = ["custom_styling"] }
dirs = "6.0"
google_maps = { version = "3.8", default-features = false, features = [
    "geocoding",
    "reqwest",
    "reqwest-default-tls",
    "decimal-serde",
] }
miette = { version = "7.6", features = ["fancy"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
tokio = { version = "1.45", default-features = false, features = ["rt"] }
toml = { version = "0.8", default-features = false, features = ["parse"] }

[profile.release]
lto = true
opt-level = "z"
strip = true
